* high priority
** (use :prefix something)
** parse extend
when parsing, parse base modules and resolve reference like alias substitution
(define twitter-follow twitter-friendship-create/sxml)
** parse current globals

** create external gosh script
delegate parsing source code

* low priority
** gather method document? comment?
** add ChangeLog 

** Renew
*** can enable change binary
/usr/local/bin/gosh
/usr/local/gosh-current/bin/gosh

if executable script
if in library buffer.
(string-match "^/usr/local/share/gauche" buffer-file-name)

can select gosh binary easily

support after install gauche completely.
In other word, execute emacs and install gauche is not supported.






** eldoc
(define hoge fuga)
means recursive fuga
** send EnvironmentVariable when evaluate 
** backend-eval error must be multiple???
dynamically put the error properties

** cannot evaluate by C-x C-e if file is invaild
 this is not acceptable(?) conduct
* refactor
** map currentenv
* BUG
** eldoc display odd
   i don't know exactly why but didn't run eldoc-print* function 
 see gosh-backend-switch-context after-change-function
